small:
  number_of_accounts: 100
  products_per_account: 30
  inheritance_ratio: 0.25
  database_suffix: small
medium:
  number_of_accounts: 1000
  products_per_account: 100
  inheritance_ratio: 0.25
  database_suffix: medium
large:
  number_of_accounts: 5000
  products_per_account: 200
  inheritance_ratio: 0.25
  database_suffix: large
  
  